#!/bin/bash

CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data1 dataset4dasl/fix_Books_train_and_valid.csv --train_data2 dataset4dasl/fix_CDs_and_Vinyl_train_and_valid.csv --test_data1 processed_data_all/Books_test.csv --test_data2 processed_data_all/CDs_and_Vinyl_test.csv --neg_data1 processed_data_all/Books_negative.csv --neg_data2 processed_data_all/CDs_and_Vinyl_negative.csv --all_metric_name ./test_metric/bc_1 >./test_results/bc_1.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 python3 train.py --de false --da false --train_data1 dataset4dasl/fix_Books_train_and_valid.csv --train_data2 dataset4dasl/fix_CDs_and_Vinyl_train_and_valid.csv --test_data1 processed_data_all/Books_test.csv --test_data2 processed_data_all/CDs_and_Vinyl_test.csv --neg_data1 processed_data_all/Books_negative.csv --neg_data2 processed_data_all/CDs_and_Vinyl_negative.csv --all_metric_name ./test_metric/bc_single_1 >./test_results/bc_single_1.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 python3 train.py --train_data1 dataset4dasl/fix_Books_train_and_valid.csv --train_data2 dataset4dasl/noisy_CDs_and_Vinyl_10_train_and_valid.csv --test_data1 processed_data_all/Books_test.csv --test_data2 processed_data_all/CDs_and_Vinyl_test.csv --neg_data1 processed_data_all/Books_negative.csv --neg_data2 processed_data_all/CDs_and_Vinyl_negative.csv --all_metric_name ./test_metric/bc_epsilon10_1 >./test_results/bc_epsilon10_1.txt 2>&1 &

CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data1 dataset4dasl/fix_Books_train_and_valid.csv --train_data2 dataset4dasl/fix_CDs_and_Vinyl_train_and_valid.csv --test_data1 processed_data_all/Books_test.csv --test_data2 processed_data_all/CDs_and_Vinyl_test.csv --neg_data1 processed_data_all/Books_negative.csv --neg_data2 processed_data_all/CDs_and_Vinyl_negative.csv --all_metric_name ./test_metric/bc_2 >./test_results/bc_2.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 python3 train.py --de false --da false --train_data1 dataset4dasl/fix_Books_train_and_valid.csv --train_data2 dataset4dasl/fix_CDs_and_Vinyl_train_and_valid.csv --test_data1 processed_data_all/Books_test.csv --test_data2 processed_data_all/CDs_and_Vinyl_test.csv --neg_data1 processed_data_all/Books_negative.csv --neg_data2 processed_data_all/CDs_and_Vinyl_negative.csv --all_metric_name ./test_metric/bc_single_2 >./test_results/bc_single_2.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 python3 train.py --train_data1 dataset4dasl/fix_Books_train_and_valid.csv --train_data2 dataset4dasl/noisy_CDs_and_Vinyl_10_train_and_valid.csv --test_data1 processed_data_all/Books_test.csv --test_data2 processed_data_all/CDs_and_Vinyl_test.csv --neg_data1 processed_data_all/Books_negative.csv --neg_data2 processed_data_all/CDs_and_Vinyl_negative.csv --all_metric_name ./test_metric/bc_epsilon10_2 >./test_results/bc_epsilon10_2.txt 2>&1 &

CUDA_VISIBLE_DEVICES=1 python3 train.py --train_data1 dataset4dasl/fix_Books_train_and_valid.csv --train_data2 dataset4dasl/fix_CDs_and_Vinyl_train_and_valid.csv --test_data1 processed_data_all/Books_test.csv --test_data2 processed_data_all/CDs_and_Vinyl_test.csv --neg_data1 processed_data_all/Books_negative.csv --neg_data2 processed_data_all/CDs_and_Vinyl_negative.csv --all_metric_name ./test_metric/bc_3 >./test_results/bc_3.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 python3 train.py --de false --da false --train_data1 dataset4dasl/fix_Books_train_and_valid.csv --train_data2 dataset4dasl/fix_CDs_and_Vinyl_train_and_valid.csv --test_data1 processed_data_all/Books_test.csv --test_data2 processed_data_all/CDs_and_Vinyl_test.csv --neg_data1 processed_data_all/Books_negative.csv --neg_data2 processed_data_all/CDs_and_Vinyl_negative.csv --all_metric_name ./test_metric/bc_single_3 >./test_results/bc_single_3.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 python3 train.py --train_data1 dataset4dasl/fix_Books_train_and_valid.csv --train_data2 dataset4dasl/noisy_CDs_and_Vinyl_10_train_and_valid.csv --test_data1 processed_data_all/Books_test.csv --test_data2 processed_data_all/CDs_and_Vinyl_test.csv --neg_data1 processed_data_all/Books_negative.csv --neg_data2 processed_data_all/CDs_and_Vinyl_negative.csv --all_metric_name ./test_metric/bc_epsilon10_3 >./test_results/bc_epsilon10_3.txt 2>&1 &
