#!/bin/bash

CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data1 dataset4dasl/fix_Movies_and_TV_train_and_valid.csv --train_data2 dataset4dasl/fix_Books_train_and_valid.csv --test_data1 processed_data_all/Movies_and_TV_test.csv --test_data2 processed_data_all/Books_test.csv --neg_data1 processed_data_all/Movies_and_TV_negative.csv --neg_data2 processed_data_all/Books_negative.csv --all_metric_name ./test_metric/mb_1 >./test_results/mb_1.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 python3 train.py --de false --da false --train_data1 dataset4dasl/fix_Movies_and_TV_train_and_valid.csv --train_data2 dataset4dasl/fix_Books_train_and_valid.csv --test_data1 processed_data_all/Movies_and_TV_test.csv --test_data2 processed_data_all/Books_test.csv --neg_data1 processed_data_all/Movies_and_TV_negative.csv --neg_data2 processed_data_all/Books_negative.csv --all_metric_name ./test_metric/mb_single_1 >./test_results/mb_single_1.txt 2>&1 &
CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data1 dataset4dasl/fix_Movies_and_TV_train_and_valid.csv --train_data2 dataset4dasl/noisy_Books_10_train_and_valid.csv --test_data1 processed_data_all/Movies_and_TV_test.csv --test_data2 processed_data_all/Books_test.csv --neg_data1 processed_data_all/Movies_and_TV_negative.csv --neg_data2 processed_data_all/Books_negative.csv --all_metric_name ./test_metric/mb_epsilon10_1 >./test_results/mb_epsilon10_1.txt 2>&1 &

CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data1 dataset4dasl/fix_Movies_and_TV_train_and_valid.csv --train_data2 dataset4dasl/fix_Books_train_and_valid.csv --test_data1 processed_data_all/Movies_and_TV_test.csv --test_data2 processed_data_all/Books_test.csv --neg_data1 processed_data_all/Movies_and_TV_negative.csv --neg_data2 processed_data_all/Books_negative.csv --all_metric_name ./test_metric/mb_2 >./test_results/mb_2.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 python3 train.py --de false --da false --train_data1 dataset4dasl/fix_Movies_and_TV_train_and_valid.csv --train_data2 dataset4dasl/fix_Books_train_and_valid.csv --test_data1 processed_data_all/Movies_and_TV_test.csv --test_data2 processed_data_all/Books_test.csv --neg_data1 processed_data_all/Movies_and_TV_negative.csv --neg_data2 processed_data_all/Books_negative.csv --all_metric_name ./test_metric/mb_single_2 >./test_results/mb_single_2.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 python3 train.py --train_data1 dataset4dasl/fix_Movies_and_TV_train_and_valid.csv --train_data2 dataset4dasl/noisy_Books_10_train_and_valid.csv --test_data1 processed_data_all/Movies_and_TV_test.csv --test_data2 processed_data_all/Books_test.csv --neg_data1 processed_data_all/Movies_and_TV_negative.csv --neg_data2 processed_data_all/Books_negative.csv --all_metric_name ./test_metric/mb_epsilon10_2 >./test_results/mb_epsilon10_2.txt 2>&1 &

CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data1 dataset4dasl/fix_Movies_and_TV_train_and_valid.csv --train_data2 dataset4dasl/fix_Books_train_and_valid.csv --test_data1 processed_data_all/Movies_and_TV_test.csv --test_data2 processed_data_all/Books_test.csv --neg_data1 processed_data_all/Movies_and_TV_negative.csv --neg_data2 processed_data_all/Books_negative.csv --all_metric_name ./test_metric/mb_3 >./test_results/mb_3.txt 2>&1 &
CUDA_VISIBLE_DEVICES=1 python3 train.py --de false --da false --train_data1 dataset4dasl/fix_Movies_and_TV_train_and_valid.csv --train_data2 dataset4dasl/fix_Books_train_and_valid.csv --test_data1 processed_data_all/Movies_and_TV_test.csv --test_data2 processed_data_all/Books_test.csv --neg_data1 processed_data_all/Movies_and_TV_negative.csv --neg_data2 processed_data_all/Books_negative.csv --all_metric_name ./test_metric/mb_single_3 >./test_results/mb_single_3.txt 2>&1 &
CUDA_VISIBLE_DEVICES=0 python3 train.py --train_data1 dataset4dasl/fix_Movies_and_TV_train_and_valid.csv --train_data2 dataset4dasl/noisy_Books_10_train_and_valid.csv --test_data1 processed_data_all/Movies_and_TV_test.csv --test_data2 processed_data_all/Books_test.csv --neg_data1 processed_data_all/Movies_and_TV_negative.csv --neg_data2 processed_data_all/Books_negative.csv --all_metric_name ./test_metric/mb_epsilon10_3 >./test_results/mb_epsilon10_3.txt 2>&1 &
